const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const New_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

export { ALERT, REFETCH_CHATS, New_ATTACHMENT, NEW_MESSAGE, NEW_REQUEST };
